os: linux
dist: xenial
language: python

jobs:
  include:
    - stage: test
      python: "3.7"
      install: pip install tox-travis
      script: tox
    - python: "3.8"
      install: pip install tox-travis
      script: tox
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        username: $PYPI_USER
        password: $PYPI_PASSWORD
        on:
          tags: true