os: linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    - stage: test
      install: pip install tox-travis
      script: tox
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        username: $PYPI_USER
        password: $PYPI_PASSWORD
        on:
          tags: true